flyway.locations=filesystem:01_ddl,filesystem:02_dml,filesystem:03_dcl,filesystem:04_tcl
flyway.validateMigrationNaming=true
flyway.cleanDisabled=true
flyway.schemas=appointment_scheduling
flyway.defaultSchema=appointment_scheduling
flyway.table=flyway_history_appointment_scheduling
flyway.baselineOnMigrate=true
flyway.baselineVersion=0
flyway.postgresql.transactional.lock=false
